### ISSUE TITLE
KeyError: 'value' hatası

### ISSUE THREAD

**Issue by ErcanYaman** [urazakgul/isyatirimhisse#8]
Selamlar,

Aşağıdaki kodda hata alınıyor. Bir ya da birden fazla sembol için IYM nin sitesinden dönen json da value bulamıyor gibi anlıyorum. 
İnceleyebilir misiniz?
KOD:
from isyatirimhisse import fetch_data
from datetime import date

data=fetch_data(
    symbol=['A1CAP','AEFES','AFYON','AGESA','AGHOL','AHGAZ','AKBNK','AKCNS','AKFGY','AKFYE','AKGRT','AKSA','AKSEN','AKSGY','ALARK','ALBRK','ALCTL','ALFAS','ALGYO','ALKIM','ANGEN','ANHYT','ANSGR','ARASE','ARCLK','ARDYZ','ARENA','ARSAN','ASELS','ASGYO','ASTOR','ASUZU','ATAKP','ATATP','AYDEM','AYEN','AYGAZ','AZTEK','BAGFS','BARMA','BASGZ','BERA','BIENY','BIGCH','BIMAS','BIOEN','BIZIM','BLCYT','BOBET','BRISA','BRKVY','BRLSM','BRSAN','BRYAT','BTCIM','BUCIM','BVSAN','CANTE','CCOLA','CEMAS','CEMTS','CIMSA','CLEBI','CONSE','CUSAN','CVKMD','CWENE','DAPGM','DESA','DEVA','DGNMO','DOAS','DOHOL','DYOBY','ECILC','ECZYT','EGEEN','EGEPO','EGGUB','EGPRO','EGSER','EKGYO','EKSUN','ELITE','ENJSA','ENKAI','ERBOS','ERCB','EREGL','ESCAR','ESCOM','ESEN','EUPWR','EUREN','FENER','FROTO','FZLGY','GARAN','GEDIK','GENIL','GENTS','GESAN','GLCVY','GLYHO','GOKNR','GOLTS','GOODY','GOZDE','GRSEL','GRTRK','GSDHO','GSRAY','GUBRF','GWIND','HALKB','HEDEF','HEKTS','HKTM','HLGYO','HTTBT','HUNER','IHAAS','IMASM','INDES','INFO','INVEO','INVES','IPEKE','ISCTR','ISDMR','ISFIN','ISGYO','ISMEN','ISSEN','IZMDC','JANTS','KAREL','KARSN','KARTN','KATMR','KAYSE','KCAER','KCHOL','KERVT','KGYO','KLGYO','KLKIM','KLMSN','KLRHO','KLSER','KLSYN','KMPUR','KNFRT','KONKA','KONTR','KONYA','KOPOL','KORDS','KOZAA','KOZAL','KRDMA','KRDMB','KRDMD','KRPLS','KRVGD','KTLEV','KTSKR','KZBGY','LIDER','LOGO','MACKO','MAGEN','MAKIM','MARTI','MAVI','MEDTR','MERCN','MGROS','MIATK','MNDRS','MNDTR','MOBTL','MPARK','MRGYO','MTRKS','NATEN','NETAS','NTGAZ','NTHOL','NUHCM','ODAS','OFSYM','ONCSM','ORGE','OTKAR','OYAKC','OYYAT','OZKGY','PAMEL','PARSN','PASEU','PENGD','PENTA','PETKM','PETUN','PGSUS','PNLSN','PNSUT','POLHO','PRDGS','PRKAB','PRKME','PSGYO','QUAGR','RUBNS','RYGYO','RYSAS','SAHOL','SARKY','SASA','SAYAS','SDTTR','SELEC','SISE','SKBNK','SMRTG','SNGYO','SNICA','SOKM','SRVGY','SUNTK','SUWEN','TATGD','TAVHL','TCELL','TERA','TEZOL','THYAO','TKFEN','TKNSA','TMSN','TOASO','TRCAS','TRGYO','TRILC','TSGYO','TSKB','TTKOM','TTRAK','TUKAS','TUPRS','TUREX','TURSG','ULKER','ULUUN','UNLU','VAKBN','VAKKO','VERUS','VESBE','VESTL','VKGYO','YATAS','YEOTK','YGGYO','YKBNK','YKSLN','YUNSA','YYLGD','ZOREN','ZRGYO','AYES','BALAT','BASCM','CMENT','ISBIR','KENT','KLNMA','KSTUR','ORMA','QNBFB','QNBFL','SNPAM','SODSN','SUMAS','TBORG','UMPAS','UZERB','YBTAS','YONGA','ATSYH','BRKO','BRMEN','CASA','DIRIT','EKIZ','EMNIS','KERVN','KUVVA','MMCAS','OTTO','ROYAL','SNKRN','ACSEL','ADEL','ADESE','AGYO','AKENR','AKMGY','AKSUE','AKYHO','ALCAR','ALKA','ALMAD','ANELE','ARZUM','ATAGY','ATEKS','ATLAS','AVGYO','AVHOL','AVOD','AVTUR','AYCES','BAKAB','BANVT','BAYRK','BEYAZ','BFREN','BJKAS','BMSCH','BMSTL','BNTAS','BOSSA','BRKSN','BSOKE','BURCE','BURVA','CELHA','CEOEM','CMBTN','COSMO','CRDFA','CRFSA','DAGHL','DAGI','DARDL','DENGE','DERHL','DERIM','DESPC','DGATE','DGGYO','DITAS','DMSAS','DNISI','DOBUR','DOCO','DOGUB','DOKTA','DURDO','DZGYO','EDATA','EDIP','EMKEL','ENSRI','EPLAS','ERSU','ETILR','ETYAT','EUHOL','EUKYO','EUYO','EYGYO','FADE','FLAP','FMIZP','FONET','FORMT','FORTE','FRIGO','GARFA','GEDZA','GEREL','GLBMD','GLRYH','GMTAS','GRNYO','GSDDE','GZNMI','HATEK','HDFGS','HUBVC','HURGZ','ICBCT','ICUGS','IDEAS','IDGYO','IEYHO','IHEVA','IHGZT','IHLAS','IHLGM','IHYAY','INGRM','INTEM','ISATR','ISBTR','ISGSY','ISKPL','ISKUR','ISYAT','ITTFH','IZFAS','IZINV','KAPLM','KARYE','KFEIN','KIMMR','KRGYO','KRONT','KRSTL','KRTEK','KUTPO','KUYAS','LIDFA','LINK','LKMNH','LUKSK','MAALT','MAKTK','MANAS','MARKA','MEGAP','MEPET','MERIT','MERKO','METRO','METUR','MIPAZ','MRSHL','MSGYO','MTRYO','MZHLD','NIBAS','NUGYO','OBASE','ORCAY','OSMEN','OSTIM','OYAYO','OYLUM','OZGYO','OZRDN','OZSUB','PAGYO','PAPIL','PCILT','PEGYO','PEKGY','PINSU','PKART','PKENT','PLTUR','POLTK','PRZMA','PSDTC','RALYH','RAYSG','RNPOL','RODRG','RTALB','SAFKR','SAMAT','SANEL','SANFM','SANKO','SEGYO','SEKFK','SEKUR','SELGD','SELVA','SEYKM','SILVR','SKTAS','SMART','SOKE','SONME','TDGYO','TEKTU','TETMT','TGSAS','TLMAN','TMPOL','TNZTP','TSPOR','TUCLK','TURGG','UFUK','ULAS','ULUFA','ULUSE','USAK','VAKFN','VANGD','VBTYZ','VERTU','VKFYO','VKING','YAPRK','YAYLA','YESIL','YGYO','YYAPI',
],
    stock_market_index=['XU100'],
    start_date='31-12-' + str((date.today().year-1)),
    end_date=date.today().strftime("%d-%m-%Y"),
    frequency='1d'
).iloc[[0, -1]].iloc[: , 1:]

YTD_return = round((data.iloc[-1] / data.iloc[0] -1 ) * 100, 2)

print(YTD_return)

HATA:
    data=fetch_data(
  File "C:\Users\200055\Anaconda3\lib\site-packages\isyatirimhisse\FetchData.py", line 104, in fetch_data
    if result['value']:
KeyError: 'value'

**Comment by urazakgul** [comment]
Selam,

Hata aşırı istek gönderimi ile alakalı olup yeni sürüm çıkarılacaktır.

**Comment by ErcanYaman** [comment]
2.1.3 sürümüyle aynı scripti çalıştırdığımda aşağıdaki hatayı aldım. Galiba IYM isteği kesiyor :)

C:\Users\200055\Anaconda3\python.exe C:\Users\200055\PycharmProjects\Egitim_1\IYM-Hisse.py 
Traceback (most recent call last):
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\200055\Anaconda3\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\Users\200055\Anaconda3\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\200055\Anaconda3\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\200055\Anaconda3\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\200055\Anaconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\200055\Anaconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\200055\Anaconda3\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\200055\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\200055\Anaconda3\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\Users\200055\Anaconda3\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\200055\Anaconda3\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\200055\Anaconda3\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\200055\Anaconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\200055\Anaconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\200055\PycharmProjects\Egitim_1\IYM-Hisse.py", line 6, in <module>
    data=fetch_data(
  File "C:\Users\200055\Anaconda3\lib\site-packages\isyatirimhisse\FetchData.py", line 108, in fetch_data
    res = requests.get(url)
  File "C:\Users\200055\Anaconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\200055\Anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\200055\Anaconda3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\200055\Anaconda3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\200055\Anaconda3\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Process finished with exit code 1

**Comment by urazakgul** [comment]
Selam, yeni sürümde bu hatanın ortadan kalkmasını bekliyorum. Bilgi vereceğim.
